id = "baklavalang"
name = "baklavalang"
version = "0.1.0"
description = "Syntax highlighting for baklavalang (.loz files)"
authors = ["baklavalang"]
schema_version = 1

[grammars.baklavalang]
repository = "https://github.com/f0t1h/baklavalang"
path = "editor/baklavalang/grammars/baklavalang"
commit = "c65c9d2"
